package com.example.hexagonalorders.infrastructure.in.web.dto;

import java.time.LocalDateTime;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.Data;

/**
 * Data Transfer Object for Delivery data.
 * This class is used to transfer delivery data between the adapter layer
 * and the application layer, keeping the domain model isolated.
 */

 @Data
public class DeliveryDto {

    @Schema(description = "Business delivery number. Generated by the backend.", example = "DEL-20240618-001", accessMode = Schema.AccessMode.READ_ONLY)
    private String deliveryNumber;

    @Schema(description = "Delivery address street.", example = "Av. San Rafael Atlixco", required = true)
    private String calle;

    @Schema(description = "Delivery address numero.", example = "186", required = true)
    private String numero;

    @Schema(description = "Delivery address colonia.", example = "Leyes de Reforma 1ra Secc", required = true)
    private String colonia;

    @Schema(description = "Delivery address ciudad.", example = "Iztapalapa", required = true)
    private String ciudad;

    @Schema(description = "Delivery address estado.", example = "CDMX", required = true)
    private String estado;

    @Schema(description = "Delivery address pais.", example = "Mexico", required = true)
    private String pais;

    @Schema(description = "Delivery creation date.", example = "2025-07-09T10:00:00", required = true)
    private LocalDateTime deliveryDate;

    @Schema(description = "Route identifier.", example = "RT-001", required = true)
    private String routeId;

    @Schema(description = "Repartidor identifier.", example = "REP-001", required = true)
    private String repartidorId;

    @Schema(description = "Order identifier.", example = "ORD-001", required = true)
    private String orderId;

    public DeliveryDto() {}

    public DeliveryDto(
        String deliveryNumber, 
        String calle, 
        String numero, 
        String colonia, 
        String ciudad, 
        String estado, 
        String pais, 
        LocalDateTime deliveryDate, 
        String routeId,
        String repartidorId,
        String orderId
    ) {
        this.deliveryNumber = deliveryNumber;
        this.calle = calle;
        this.numero = numero;
        this.colonia = colonia;
        this.ciudad = ciudad;
        this.estado = estado;
        this.pais = pais;
        this.deliveryDate = deliveryDate;
        this.routeId = routeId;
        this.repartidorId = repartidorId;
        this.orderId = orderId;
    }

    public String getDeliveryNumber() {
        return deliveryNumber;
    }

    public String getCalle() {
        return calle;
    }

    public String getNumero() {
        return numero;
    }

    public String getColonia() {
        return colonia;
    }

    public LocalDateTime getDeliveryDate() {
        return deliveryDate;
    }

    public String getRouteId() {
        return routeId;
    }

    public String getRepartidorId() {
        return repartidorId;
    }

    public String getOrderId() {
        return orderId;
    }
} 