name: CI/CD Multi-Service Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_PREFIX: ${{ github.repository_owner }}
  IMAGE_EVENT: event-service
  IMAGE_ORDER: order-service

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and test EventOrder
        working-directory: ./EventOrder
        run: |
          mvn clean package
          mvn test
          mvn jacoco:report

      - name: Build and test EventDelivery
        working-directory: ./EventDelivery
        run: |
          mvn clean package
          mvn test
          mvn jacoco:report

  build-and-push-docker:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push EventOrder image
        uses: docker/build-push-action@v5
        with:
          context: ./EventOrder
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_EVENT }}:latest

      - name: Build and push EventDelivery image
        uses: docker/build-push-action@v5
        with:
          context: ./EventDelivery
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_PREFIX }}/${{ env.IMAGE_ORDER }}:latest

      - name: Build and up docker-compose
        run: |
          docker compose build
          docker compose up -d